spring:
  zipkin:
    enabled: false
    baseUrl: http://localhost:9411/
  application:
    name: demo-service
  cloud:
    bus:
      enabled: false
    discovery:
      enabled: false
    consul:
      enabled: false
      config:
        enabled: false
#      host: localhost
#      port: 8500
server:
  port: 8081


management:
  endpoints:
    web:
      exposure:
        include: "*"