spring:
  application:
    name: demo-service
  cloud:
    consul:
      host: consul-consul-server
      port: 8500
server:
  port: 8081

zipkin:
  enabled: false
  baseUrl: http://localhost:9411/

management:
  endpoints:
    web:
      exposure:
        include: "*"