spring:
  zipkin:
    enabled: false
    baseUrl: http://localhost:9411/
  application:
    name: demo-service
  cloud:
    bus:
      enabled: true
    discovery:
      enabled: true
    consul:
      enabled: true
      config:
        enabled: true
      host: hashicorp-consul-server
      port: 8500
server:
  port: 8081


management:
  endpoints:
    web:
      exposure:
        include: "*"